# Generated by Django 2.1.1 on 2019-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('sub', models.CharField(blank=True, max_length=50)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
